### ISSUE TITLE
examples/C/r1cs/add.c apparently set up for MPC?

### ISSUE THREAD

**Issue by kwantam** [circify/circ#95]
https://github.com/circify/circ/blob/e362f9501ba7d74706a34cc9ac129d96cdde673d/examples/C/r1cs/add.c#L1-L6

The `mpc_main` function here seems to imply that it's set up for MPC, but it's in the R1CS directory. @edwjchen is this expected or is this an error?

**Comment by kwantam** [comment]
Separately, are we using `mpc_main` for the MPC back-end(s) for some reason? I assume there's a reason that simply using `main` wouldn't work, right? What is that reason, if so? (@edwjchen ? @alex-ozdemir ?)

**Comment by edwjchen** [comment]
This must be an artifact left over from copying another example. `mpc_main` shouldn't work and should be replaced with `main`.

**Comment by kwantam** [comment]
Great, thanks. I'll fix it.

**Comment by pag-crypto** [comment]
This didn't fix the issue for me, I see 

`thread 'main' panicked at 'not implemented', src/front/c/mod.rs:1104:21`

Verbose stacktrace is below.

```
Options { path: "examples/C/r1cs/add.c", frontend: FrontendOptions { language: Auto, value_threshold: None, rec_limit: 5, lint_prim_rec: false, z_isolate_asserts: false }, parties: 2, backend: R1cs { prover_key: "P", verifier_key: "V", lc_elimination_thresh: 50, action: Count } }
thread 'main' panicked at 'not implemented', src/front/c/mod.rs:1104:21
stack backtrace:
   0:        0x102f666e0 - std::backtrace_rs::backtrace::libunwind::trace::ha03082fdb36b8e44
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x102f666e0 - std::backtrace_rs::backtrace::trace_unsynchronized::hf1acb3d3fce46837
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x102f666e0 - std::sys_common::backtrace::_print_fmt::hbc7deaf5374edfd8
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:66:5
   3:        0x102f666e0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha9a1a8bf7485458d
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:45:22
   4:        0x102f83830 - core::fmt::write::h9ee5b099821ae5e1
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/fmt/mod.rs:1196:17
   5:        0x102f62d50 - std::io::Write::write_fmt::h240449cbf2a536ee
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/io/mod.rs:1654:15
   6:        0x102f67f90 - std::sys_common::backtrace::_print::hf65124e94f800e0d
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:48:5
   7:        0x102f67f90 - std::sys_common::backtrace::print::haec7f207d91c0faa
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:35:9
   8:        0x102f67f90 - std::panicking::default_hook::{{closure}}::h321649ccf26de565
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:295:22
   9:        0x102f67c6c - std::panicking::default_hook::h1e736e6294672e8d
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:314:9
  10:        0x102f68468 - std::panicking::rust_panic_with_hook::hd083a3aa5c934ce6
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:698:17
  11:        0x102f68324 - std::panicking::begin_panic_handler::{{closure}}::hb5be8aaa10a229ca
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:586:13
  12:        0x102f66bbc - std::sys_common::backtrace::__rust_end_short_backtrace::h68e10e4f00198298
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:138:18
  13:        0x102f680b4 - rust_begin_unwind
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
  14:        0x102facde0 - core::panicking::panic_fmt::hffc63a015c61fdde
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
  15:        0x102facd00 - core::panicking::panic::h5978a1941192adf2
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:48:5
  16:        0x102d5a7a0 - circ::front::c::CGen::entry_fn::h191ebc013f642b0c
                               at /Users/paulgrubbs/research/circ/src/front/c/mod.rs:1104:21
  17:        0x102d5a7a0 - <circ::front::c::C as circ::front::FrontEnd>::gen::h0274061e1942f609
                               at /Users/paulgrubbs/research/circ/src/front/c/mod.rs:45:9
  18:        0x102c097e8 - circ::main::hd4ee872a8a1156b1
                               at /Users/paulgrubbs/research/circ/examples/circ.rs:216:13
  19:        0x102c0f348 - core::ops::function::FnOnce::call_once::he427462ab740f47c
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
  20:        0x102c0f348 - std::sys_common::backtrace::__rust_begin_short_backtrace::hfbeeafe607e0aed1
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:122:18
  21:        0x102bea99c - std::rt::lang_start::{{closure}}::hc5aaf4e2de143992
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:145:18
  22:        0x102f5da80 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h3b331d3fbbcc71c7
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:280:13
  23:        0x102f5da80 - std::panicking::try::do_call::hff616b6be7bbc015
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:492:40
  24:        0x102f5da80 - std::panicking::try::h298ba2ba2d72fd07
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:456:19
  25:        0x102f5da80 - std::panic::catch_unwind::h82d7a0ad94159423
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panic.rs:137:14
  26:        0x102f5da80 - std::rt::lang_start_internal::{{closure}}::h801a38d4a43d99be
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:128:48
  27:        0x102f5da80 - std::panicking::try::do_call::h8ecac938bf293f4a
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:492:40
  28:        0x102f5da80 - std::panicking::try::he8bacc15da046b2c
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:456:19
  29:        0x102f5da80 - std::panic::catch_unwind::hfbee3bd78d2873c3
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panic.rs:137:14
  30:        0x102f5da80 - std::rt::lang_start_internal::hbbfe6e663b24763e
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:128:20
  31:        0x102c0bb60 - _main

```

**Comment by pag-crypto** [comment]
Getting rid of the attribute declarations and running this program:

```
int main(
    int a,
    int b)
{
    return a + b;
}
```

fails also, complaining about a bad visibility declaration. Trace is below:

```
Options { path: "examples/C/r1cs/add.c", frontend: FrontendOptions { language: Auto, value_threshold: None, rec_limit: 5, lint_prim_rec: false, z_isolate_asserts: false }, parties: 2, backend: R1cs { prover_key: "P", verifier_key: "V", lc_elimination_thresh: 50, action: Count } }
thread 'main' panicked at 'Bad visibility declaration.', src/front/c/ast_utils.rs:163:5
stack backtrace:
   0:        0x10324e6e0 - std::backtrace_rs::backtrace::libunwind::trace::ha03082fdb36b8e44
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x10324e6e0 - std::backtrace_rs::backtrace::trace_unsynchronized::hf1acb3d3fce46837
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10324e6e0 - std::sys_common::backtrace::_print_fmt::hbc7deaf5374edfd8
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:66:5
   3:        0x10324e6e0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha9a1a8bf7485458d
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:45:22
   4:        0x10326b830 - core::fmt::write::h9ee5b099821ae5e1
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/fmt/mod.rs:1196:17
   5:        0x10324ad50 - std::io::Write::write_fmt::h240449cbf2a536ee
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/io/mod.rs:1654:15
   6:        0x10324ff90 - std::sys_common::backtrace::_print::hf65124e94f800e0d
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:48:5
   7:        0x10324ff90 - std::sys_common::backtrace::print::haec7f207d91c0faa
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:35:9
   8:        0x10324ff90 - std::panicking::default_hook::{{closure}}::h321649ccf26de565
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:295:22
   9:        0x10324fc6c - std::panicking::default_hook::h1e736e6294672e8d
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:314:9
  10:        0x103250468 - std::panicking::rust_panic_with_hook::hd083a3aa5c934ce6
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:698:17
  11:        0x1030b7f48 - std::panicking::begin_panic::{{closure}}::hccc455bc5794420d
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:617:9
  12:        0x1030b7f1c - std::sys_common::backtrace::__rust_end_short_backtrace::h17172a9165e08cce
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:138:18
  13:        0x103278694 - std::panicking::begin_panic::ha23f40eaa10b0a81
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:616:12
  14:        0x1030ca92c - circ::front::c::ast_utils::interpret_visibility::hdb37ab30f3b59aed
                               at /Users/paulgrubbs/research/circ/src/front/c/ast_utils.rs:163:5
  15:        0x1030449c8 - circ::front::c::CGen::get_param_info::head5ed3a6e83e917
                               at /Users/paulgrubbs/research/circ/src/front/c/mod.rs:288:19
  16:        0x103041cb4 - circ::front::c::CGen::entry_fn::h191ebc013f642b0c
                               at /Users/paulgrubbs/research/circ/src/front/c/mod.rs:1070:30
  17:        0x103041cb4 - <circ::front::c::C as circ::front::FrontEnd>::gen::h0274061e1942f609
                               at /Users/paulgrubbs/research/circ/src/front/c/mod.rs:45:9
  18:        0x102ef17e8 - circ::main::hd4ee872a8a1156b1
                               at /Users/paulgrubbs/research/circ/examples/circ.rs:216:13
  19:        0x102ef7348 - core::ops::function::FnOnce::call_once::he427462ab740f47c
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
  20:        0x102ef7348 - std::sys_common::backtrace::__rust_begin_short_backtrace::hfbeeafe607e0aed1
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:122:18
  21:        0x102ed299c - std::rt::lang_start::{{closure}}::hc5aaf4e2de143992
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:145:18
  22:        0x103245a80 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h3b331d3fbbcc71c7
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:280:13
  23:        0x103245a80 - std::panicking::try::do_call::hff616b6be7bbc015
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:492:40
  24:        0x103245a80 - std::panicking::try::h298ba2ba2d72fd07
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:456:19
  25:        0x103245a80 - std::panic::catch_unwind::h82d7a0ad94159423
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panic.rs:137:14
  26:        0x103245a80 - std::rt::lang_start_internal::{{closure}}::h801a38d4a43d99be
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:128:48
  27:        0x103245a80 - std::panicking::try::do_call::h8ecac938bf293f4a
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:492:40
  28:        0x103245a80 - std::panicking::try::he8bacc15da046b2c
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:456:19
  29:        0x103245a80 - std::panic::catch_unwind::hfbee3bd78d2873c3
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panic.rs:137:14
  30:        0x103245a80 - std::rt::lang_start_internal::hbbfe6e663b24763e
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:128:20
  31:        0x102ef3b60 - _main
```

**Comment by pag-crypto** [comment]
Removing the `unimplemented!();` statement on line 1104 of src/front/c/mod.rs appears to fix this, but it's not yet clear to me if CirC is working correctly - the generated R1CS has size 0, and still has size 0 even if I replace the addition with a multiplication in add.c (so the program simply is `return a*b;`).

**Comment by edwjchen** [comment]
@pag-crypto As you mentioned, removing the [unimplemented!();](https://github.com/circify/circ/blob/20198e9012367c0ef51021ce38d22a5556bfd063/src/front/c/mod.rs#L1104) will fix the non-implemented error. C->r1cs pipeline was blocked by this statement mainly because I was primarily targeting C->mpc, and only added this testcase example for r1cs->spartan backend to reference.

It seems that the output terms are being removed by the [Inline](https://github.com/circify/circ/blob/20198e9012367c0ef51021ce38d22a5556bfd063/examples/circ.rs#L259) optimization pass. If I comment out these optimizations [here](https://github.com/circify/circ/blob/20198e9012367c0ef51021ce38d22a5556bfd063/examples/circ.rs#L259) and [here](https://github.com/circify/circ/blob/20198e9012367c0ef51021ce38d22a5556bfd063/examples/circ.rs#L271),  then I get:
```
Converting to r1cs
Pre-opt R1cs size: 134
Final R1cs size: 129
0.00 seconds 14212 kB
```

@kwantam I don't have much experience with the r1cs backend, is this the intended behavior?

**Comment by kwantam** [comment]
@edwjchen I doubt this is the intended behavior...

@pag-crypto what happens if you mark both `a` and `b` with `__attribute__((public))` and change the body to `return a * b;` (*without* removing the inline optimization passes)?

**Comment by pag-crypto** [comment]
Same thing - the R1CS has size 0.

**Comment by pag-crypto** [comment]
Any update on this?
